language: cpp

os: linux
dist: bionic

matrix:
  include:
    - name: "Mac OSX (Xcode 11.3)"
      os: osx
      osx_image: xcode11.3
      env:
        DEPS_ARCH=x64-osx
    - name: "Linux (Clang)"
      os: linux
      compiler: clang
      env:
        DEPS_ARCH=x64-linux
    - name: "Linux (GCC)"
      os: linux
      compiler: gcc
      env:
        DEPS_ARCH=x64-linux

script:
  - mkdir build
  - pushd build
  - cmake -DDEPS_ROOT=../${DEPS_ARCH} ../example
  - make
  - make test
  - popd

  - shellcheck ./build.sh
  # rebuilding the artifacts happens after building the example to confirm the example is working
  # with the artifacts as checked in.
  # This can take a long time, so it is disabled for now.
  # - ./build.sh
